# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: required

dist: bionic
language: scala
scala:
  - 2.12.10
jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - name: Test Kyuubi w/ Default Profile
      env:
        - PROFILE=""
        - JOB="build"
        - CODECOV="true"
    - name: Test Kyuubi w/ -Pspark-3.0 and Spark 3.1 binary
      env:
        - PROFILE="-Pspark-3.0 -Dspark.archive.mirror=https://archive.apache.org/dist/spark/spark-3.1.2 -Dspark.archive.name=spark-3.1.2-bin-hadoop2.7.tgz -Dmaven.plugin.scalatest.exclude.tags=org.apache.kyuubi.tags.ExtendedSQLTest,org.apache.kyuubi.tags.DeltaTest,org.apache.kyuubi.tags.IcebergTest"
        - JOB="build"
    - name: Test Kyuubi w/ -Pspark-3.1 -Pkyuubi-extension-spark_3.1
      env:
        - PROFILE="-Pspark-3.1 -Pkyuubi-extension-spark_3.1"
        - JOB="build"
    - name: Test Kyuubi w/ -Pspark-master
      env:
        - PROFILE="-Pspark-master"
        - JOB="nightly-build"
    - name: Test Kyuubi w/ -Pspark-3.1 TPCDS Tests
      env:
        - PROFILE="-Pspark-3.1 -Dmaven.plugin.scalatest.exclude.tags=''"
        - JOB="tpcds-tests"

install:
  - ./build/mvn --version

script:
  - |
    if [[ "$TRAVIS_EVENT_TYPE" != "cron" && "$JOB" == "build" ]]; then
      ./build/mvn clean install $PROFILE -Dmaven.javadoc.skip=true -V
    fi
  - |
    if [[ "$TRAVIS_EVENT_TYPE" == "cron" && "$JOB" == "nightly-build" ]]; then
      ./build/mvn clean install $PROFILE -pl :kyuubi-spark-sql-engine,:kyuubi-common,:kyuubi-ha,:kyuubi-zookeeper -Dmaven.javadoc.skip=true -V
    fi
  - |
    if [[ "$TRAVIS_EVENT_TYPE" != "cron" && "$JOB" == "tpcds-tests" ]]; then
      ./build/mvn clean install $PROFILE -DskipTests -pl :kyuubi-spark-sql-engine,:kyuubi-common,:kyuubi-ha,:kyuubi-zookeeper
      ./build/mvn test $PROFILE -Dtest=none -DwildcardSuites=org.apache.kyuubi.operation.tpcds
    fi

after_success:
  - if [[ "$CODECOV" == "true" ]]; then bash <(curl -s https://codecov.io/bash); fi

after_failure:
  - echo "==== Build with $PROFILE FAILED ===="
  - for log in `find * -name "kyuubi-spark-sql-engine.log*"`; do echo "=========$log========="; cat $log; done
  - for log in `find * -name "unit-tests.log"`; do echo "=========$log========="; cat $log; done
