language: scala
scala:
  - 2.12.10
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - ./build

deploy:
  - provider: pages
    cleanup: false
    keep_history: true
    github_token: $GITHUB_TOKEN
    email: yaooqinn@hotmail.com
    name: Kent Yao
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: kyuubi-*.tar.gz
    cleanup: false
    on:
      tags: true

install:
  - build/mvn --version

#jobs:
#  include:
#    - stage: spark3.0.0
#      script:
#        - build/mvn --no-transfer-progress clean verify -pl :kyuubi-common,:kyuubi-ha,:kyuubi-main,:kyuubi-spark-sql-engine,:kyuubi-codecov,:kyuubi-download,:kyuubi-assembly -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean install -pl '!:kyuubi-server,!:kyuubi-thrift' -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)
